This file contains several test cases to test the add_integer function

import the add_integer function from 0-add_integer module

	>>> add_integer = __import__('0-add_integer').add_integer

The following are the test cases:

	>>> add_integer(2)
	100
	>>> add_integer(2, 4)
	6
	>>> add_integer(-2, -2)
	-4
	>>> add_integer(1, -1)
	0
	>>> add_integer(-2)
	96
	>>> add_integer(2, 'H')
	Traceback (most recent call last):
		...
	TypeError: b must be an integer
	>>> add_integer('A', 2)
	Traceback (most recent call last):
		...
	TypeError: a must be an integer
	>>> add_integer(None)
	Traceback (most recent call last):
		...
	TypeError: a must be an integer
	>>> add_integer(2, None)
	Traceback (most recent call last):
		...
	TypeError: b must be an integer
	>>> add_integer([2, 3, 4], 2)
	Traceback (most recent call last):
		...
	TypeError: a must be an integer
	>>> add_integer(2, [2, 3, 4])
	Traceback (most recent call last):
		...
	TypeError: b must be an integer
	>>> add_integer((2, 3, 4), 2)
        Traceback (most recent call last):
                ...
        TypeError: a must be an integer
        >>> add_integer(2, (2, 3, 4))
        Traceback (most recent call last):
                ...
        TypeError: b must be an integer
	>>> add_integer(0)
	98
	>>> add_integer(0, 0)
	0
	>>> add_integer(30.23, 2)
	32
	>>> add_integer(2, 2.22)
	4
	>>> add_integer(3.1, 3.1)
	6
